# Generated by Django 3.1 on 2020-12-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.EmailField(max_length=254)),
                ('time', models.TextField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('mobile', models.CharField(max_length=12)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField()),
                ('dname', models.TextField(max_length=122)),
                ('dquantity', models.IntegerField()),
                ('damount', models.IntegerField()),
            ],
            options={
                'db_table': 'dish',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.EmailField(max_length=254)),
                ('dishname', models.TextField(max_length=200)),
                ('dishprice', models.IntegerField()),
                ('dishtype', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
    ]
